[versions]
agp = "8.13.2"
concentus = "1.0.2"
# Forked build of 6.3.2
jda = "6.3.2_DEV"
# Forked build of ce725965e
libdave = "eec9c3e66"
kotlin = "2.2.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
constraintlayout = "2.1.4"
oboe = "1.9.0"

[libraries]
libdaveimpljni = { module = "moe.kyokobot.libdave:impl-jni", version.ref = "libdave" }
libdaveadapterjda = { module = "moe.kyokobot.libdave:adapter-jda", version.ref = "libdave" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
concentus = { module = "io.github.jaredmdobson:concentus", version.ref = "concentus" }
jda = { module = "net.dv8tion:JDA", version.ref = "jda" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
oboe = { module = "com.google.oboe:oboe", version.ref = "oboe" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

